# Generated by Django 3.2.4 on 2021-06-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('credentials', models.CharField(max_length=25)),
                ('blogPost', models.TextField()),
                ('blogImage', models.ImageField(upload_to='media')),
            ],
        ),
    ]
